### ISSUE TITLE
LV - v2.2 release - Downloading default log file is not named correctly

### ISSUE THREAD

**Issue by trumpy81** [dagalufh/WebTools.bundle#165] opened 2016-04-26 01:59 UTC
When viewing the default Plex Media Server.log file in Log Viewer and you click on 'download selected logfile', the file name of said log file is saved as 'Plex' with no file extension.

The same applies for any file name containing a space, only the first word is used for the file name.

WT is installed on Synology NAS. I will test the PC install later on when I have time and report back.

**Comment by dagalufh** [comment] 2016-04-26 04:49
I have a suspision that this might be on my end, not sure but i'll check it out.

**Comment by ukdtom** [comment] 2016-05-06 00:03
Working fine here

**Comment by trumpy81** [comment] 2016-05-06 01:02
I checked this behaviour in IE, Edge and Chrome and I don't have any issues with them, but in FireFox I do, see the attached image.

Could be the mime type in FireFox perhaps??

![untitled-1](https://cloud.githubusercontent.com/assets/12381786/15061491/835c7630-1379-11e6-91d3-cfbbfe4c182e.jpg)

**Comment by ukdtom** [comment] 2016-05-06 01:24
Confirmed this to be a Firefox issue only......

Seen the same thing using that :-(


/T

**Comment by dagalufh** [comment] 2016-05-06 05:05
Have a theory for fix, i'll see if i have time tonight to test it.
Den 6 maj 2016 03:24 skrev "Tommy Mikkelsen" <notifications@github.com>:

**Comment by dagalufh** [comment] 2016-05-17 08:12
Fix included in next release...

**Comment by ukdtom** [comment] 2016-05-26 20:49
Sadly not fixed, still see this

**Comment by dagalufh** [comment] 2016-05-27 05:18
Is it only the default that is not available for download or is it any of the logfiles?

**Comment by ukdtom** [comment] 2016-05-27 06:43
All of them.

And they are all avail, so maybe you are missing the point here:

When a log to download contains a space in it's name, the proposed filename to save get's cut of at the space.

Like "Plex Media Server.log" is saved as "Plex"

**Comment by dagalufh** [comment] 2016-05-27 07:03
Can you please right click on the element, select box, and do an inspect and show me, via screenshot or something, what it looks like in the code?

It should look something like this:

![image](https://cloud.githubusercontent.com/assets/8938352/15600390/d54220f0-23e9-11e6-97d4-ad8b566a7b9e.png)

**Comment by ukdtom** [comment] 2016-05-27 18:06
![mozilla](https://cloud.githubusercontent.com/assets/4699449/15616827/5976d260-2446-11e6-92ef-e23615891cae.png)

Above taken in Mozilla firefox, and sadly looks okay, so guess it's the function call to save, that behaves differently in firefox

**Comment by dagalufh** [comment] 2016-05-27 18:09
Hmm. Can we use some other form of delimiter for space? That you can than
translate to space? Any ideas? How about using + (plus sign)? That is not
usdd in any filenames. Or perhaps / one forward slash?
Den 27 maj 2016 8:06 em skrev "Tommy Mikkelsen" <notifications@github.com>:

**Comment by ukdtom** [comment] 2016-05-27 20:32
Heh.....It's in my end!

Hopefully fixed in https://github.com/dagalufh/WebTools.bundle/commit/c20c8f26c5a1dfc195f02b9c5af5e6d5076bcb05

Found this:

http://kb.mozillazine.org/Filenames_with_spaces_are_truncated_upon_download

Updated my branch with a fix, hopefully, and did check with both Chrome, IE11, Edge and Firefox, but would like a confirmation from you @trumpy81 if possible?
Grab my branch to test it, and maybe also FindMedia ;-)

@dagalufh Do note that I also updated logviewer.js with additional logging ;-)

/T

**Comment by trumpy81** [comment] 2016-05-27 23:52
There is also an issue of Firefox 46.0.1 downloading the file as a PDF instead of a text file, although that may be caused by my extremely slow net connection, I was barely able to load this page, so I will have to wait until 1st June when I get unlimited download and no throttling.

Until then I am pretty much offline :(

I do see where the issue appears to be part of the mime type definition, so that may also correct the PDF issue, I will test it as soon as I can.

**Comment by ukdtom** [comment] 2016-06-25 20:45
@trumpy81 Got better Internet Access now?

**Comment by trumpy81** [comment] 2016-06-25 21:46
Yes I have thanks. :)

 I did report my findings to you, but I completely forgot about this GHI, sorry about that.

Using the 2.3 Dev version, I have no issues with missing file names or incorrect filetypes when using Firefox 47.0. :)

**Comment by ukdtom** [comment] 2016-06-25 22:30
Thanks

**Closed by ukdtom** 2016-06-25 22:30 UTC
Labels: bug
