### ISSUE TITLE
Error while deleting any subtitle (Sub-Zero, and file stored within metadata)

### ISSUE THREAD

**Issue by acs-ferreira** [dagalufh/WebTools.bundle#197] opened 2016-10-13 17:57 UTC
Select Subtitle > Delete Selected >Yes

`{"readyState":4,"responseText":"Fatal error happened in delSub: bad argument type for built-in operation","status":500,"statusText":"Internal Server Error"}`

This error occurs in ANY subtitle for ANY media, choosing one or more subtitles to delete.

PS: Is there a way to delete ALL subtitles for ALL medias ?

**Comment by ukdtom** [comment] 2016-10-15 12:21
Working fine here, so I need you do reproduce, and then zip all of WebTools log files and upload here

**Comment by ukdtom** [comment] 2016-10-15 12:23
And adding.....Nope, there's no option to delete all in one go, and also not going to happen, since IMHO too dangerous.

When said, if those where downloaded by an agent, then I "think" you simply could remove/disable the agent, and they'll be gone

**Comment by acs-ferreira** [comment] 2016-10-17 19:20
Here is the WebTools LOG file.
Noted for how to delete all subtitles, thanks!

[com.plexapp.plugins.WebTools.txt](https://github.com/dagalufh/WebTools.bundle/files/534475/com.plexapp.plugins.WebTools.txt)

**Comment by acs-ferreira** [comment] 2016-10-17 19:22
Please note that i'm using METADATA only as storage.

**Comment by ukdtom** [comment] 2016-10-17 19:39
Well.....This is embarrassing.

The sub was downloaded from Sub-Zero, and regardless I wrote the Wiki for it, and contribute to it, I don't support it :-(

I'll see what I can do for the next release though

**Comment by acs-ferreira** [comment] 2016-10-17 20:37
Ok i see... thanks :)

**Comment by ukdtom** [comment] 2016-10-17 22:34
Fixed in https://github.com/dagalufh/WebTools.bundle/commit/d0835f44ec4588a18e3a97b1c2f630ed82df8dfc

Will be part of next release

**Comment by acs-ferreira** [comment] 2016-10-18 14:35
Great, thanks :)

**Comment by acs-ferreira** [comment] 2016-10-27 10:37
Not fixed on my side on 2.3 release :(

**Comment by acs-ferreira** [comment] 2016-10-27 10:38
> When said, if those where downloaded by an agent, then I "think" you simply could remove/disable the agent, and they'll be gone

Doesn't work either. :(

**Comment by ukdtom** [comment] 2016-11-15 19:29
Recheck again, and it worked fine with a sub downloaded by SZ and stored as an agent based sub.

Did however notice, that about 30 sec. later, SZ redownloaded it again ;-)

So please recheck that this is maybe what you see

**Comment by ukdtom** [comment] 2016-12-06 22:01
Closed due to lack of response

**Closed by ukdtom** 2016-12-06 22:01 UTC
Labels: bug, Critical, Feedback needed
