### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by rimsky82** [dagalufh/WebTools.bundle#125] opened 2016-01-21 04:01 UTC
New to the plugin, loaded it up fresh.  But going to http://<myip>:33400 results in a 500: internal server error.

**Comment by SvenErik1968** [comment] 2016-01-21 05:45
I also get the same error.

**Comment by ukdtom** [comment] 2016-01-21 07:26
If on Linux, then run: sudo chown plex:plex ./WebTools.bundle -R

**Comment by SvenErik1968** [comment] 2016-01-21 07:38
I am on Windows Server 2008 R2.

**Comment by ukdtom** [comment] 2016-01-21 07:48
Then I need the webtools logs, as well as a bit more info, like when it happens

**Comment by SvenErik1968** [comment] 2016-01-21 07:50
I will upload the logs when I get home from work later today.
It happens from the start when trying to launch the page.

**Comment by SvenErik1968** [comment] 2016-01-21 15:09
When I try to access the WebTools page at `http://10.0.0.68:33400/` the URL get changed to `http://10.0.0.68:33400/login?next=%2F` (I assume that is correct) and I get an "500: Internal Server Error" message.

I have added all the plugin logs from this plugin that has been generated since I installed it.

I am running Plex v0.9.15.1 on a Windows Server 2008 R2.

[com.plexapp.plugins.WebTools.logs.zip](https://github.com/dagalufh/WebTools.bundle/files/99309/com.plexapp.plugins.WebTools.logs.zip)

**Comment by ukdtom** [comment] 2016-01-22 00:30
Sadly tried everything I could think of to duplicate, but sadly can't :-(

Sorry, but clueless here

**Comment by SvenErik1968** [comment] 2016-01-22 10:39
OK, I will do an uninstall and clean install of Plex this weekend to see if that helps.

**Comment by ukdtom** [comment] 2016-01-22 16:55
Please report back, cuz so puzzled here

**Comment by SvenErik1968** [comment] 2016-01-22 20:58
I still get the same error after uninstalling (but leaving the metadata) and installing again.
The log file does not give any clues as far as I can see.
The com.plexapp.system.log file has some error messages, but not sure if they are relevant:

    2016-01-22 21:40:43,884 (2df4) :  DEBUG (runtime:717) - Handling request GET /system/notify/serverUpdated?host=10.0.0.68
    2016-01-22 21:40:43,884 (2df4) :  DEBUG (runtime:814) - Found route matching /system/notify/serverUpdated
    2016-01-22 21:40:43,884 (2df4) :  DEBUG (logkit:13) - Handling server update notification (10.0.0.68)
    2016-01-22 21:40:43,884 (2df4) :  DEBUG (logkit:13) - Updating servers (False/False True/True/True)
    2016-01-22 21:40:43,885 (2df4) :  DEBUG (logkit:13) - Fetching the current list of servers
    2016-01-22 21:40:43,885 (2df4) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/servers'
    2016-01-22 21:40:43,891 (2df4) :  DEBUG (logkit:13) - Found 1 servers
    2016-01-22 21:40:43,891 (2df4) :  DEBUG (logkit:13) - Updating existing server Brage (7984d80f78548f924f031ee4a7064adc8a9b92ac)
    2016-01-22 21:40:43,891 (2df4) :  DEBUG (networking:166) - Requesting 'http://10.0.0.68:32400/library/sections'
    2016-01-22 21:40:43,898 (2df4) :  ERROR (networking:217) - Error opening URL 'http://10.0.0.68:32400/library/sections'
    2016-01-22 21:40:43,898 (2df4) :  ERROR (logkit:22) - Failed to fetch data from http://10.0.0.68:32400/library/sections: ()
    2016-01-22 21:40:43,900 (2df4) :  DEBUG (networking:166) - Requesting 'http://10.0.0.68:32400/channels/all'
    2016-01-22 21:40:43,905 (2df4) :  ERROR (networking:217) - Error opening URL 'http://10.0.0.68:32400/channels/all'
    2016-01-22 21:40:43,907 (2df4) :  ERROR (logkit:22) - Failed to fetch data from http://10.0.0.68:32400/channels/all: ()
    2016-01-22 21:40:43,907 (2df4) :  DEBUG (runtime:924) - Response: [200] str, 0 bytes

A last resort effort would be to do a complete install from scratch, but not a very tempting task considering I have about 4300 movies and 800 series with about 27.300 episodes...

[com.plexapp.plugins.WebTools.zip](https://github.com/dagalufh/WebTools.bundle/files/101422/com.plexapp.plugins.WebTools.zip)

**Comment by ukdtom** [comment] 2016-01-22 21:07
Are you perhaps running PMS as a service, meaning as another user, and that user has no rights to the WebTools.bundle directory?

Cuz sadly still nothing in the logs :-(

**Comment by rimsky82** [comment] 2016-01-22 21:10
In my case I'm running it as myself, I tried messing with permissions but no go.

**Comment by ukdtom** [comment] 2016-01-22 21:12
And you gave me nothing to work with !

I need logs here!

**Comment by rimsky82** [comment] 2016-01-22 21:15
[com.plexapp.plugins.WebTools.zip](https://github.com/dagalufh/WebTools.bundle/files/101447/com.plexapp.plugins.WebTools.zip)
it's better than bad, it's good

**Comment by SvenErik1968** [comment] 2016-01-22 21:19
Yes, I am using the [Plex Service wrapper](https://github.com/cjmurph/PmsService), but it is running with the same user as Plex itself and that user has full access to all the directories under Plex.

**Comment by ukdtom** [comment] 2016-01-22 21:38
okay and both of you.....

Since on windows....Are you perhaps running some kinda AntiVira solution, or http inspection util, that could have an influence on this?

**Comment by ukdtom** [comment] 2016-01-22 21:39
And @rimsky82 Sadly also nothing in your log, though it seems it's getting further in the execution here

**Comment by SvenErik1968** [comment] 2016-01-22 21:41
I am running Trend Micro Internet Security, but it has never had any affect on Plex or third-party plugins like plex2csv or Sub-Zero I have had running before I tried WebTools.

**Comment by rimsky82** [comment] 2016-01-22 21:43
Windows Defender as built into Windows 10.

**Comment by ukdtom** [comment] 2016-01-22 21:45
Care for a small test, and not optimistic here, to turn them off. then try again?
But just to rule that part out ;-)

**Comment by ukdtom** [comment] 2016-01-22 21:46
Ohh, and @SvenErik1968 Thanks for using Plex2CSV ;-)
Do hope that works better for you

**Comment by rimsky82** [comment] 2016-01-22 21:46
No change

**Comment by SvenErik1968** [comment] 2016-01-22 21:49
No change here either.

I **LOVE** Plex2CSV! Since Plex has no option to filter in available audio and/or subtitle languages, I use it to find movies/series to add to specific collections based on the languages.

**Comment by ukdtom** [comment] 2016-01-22 21:55
@SvenErik1968 Thanks mate, one out of two is better than none I guess

@rimsky82  @SvenErik1968 
Sadly clueless for the moment now, since I simply can't reproduce, and FUI, download count started after day 3, and so far, we have 1703 downloads, and sadly you two as well as one user on Reddit has it running perfectly, and common thing for you 3 is, that you all are on Windows.
Sadly still have to track this down, and have so far tried every thing I can think about :-(
Only thing left, is for you to check your PMS log, as well as your system log for clues, since there's nothing in the WebTools logs

**Comment by SvenErik1968** [comment] 2016-01-22 22:14
I have looked through the Plex and system logs without any clues...
So going to drop this attempt to use WebTools for now. As long as Plex2CSV and Sub-Zero will be available for manual install I have the most essential tools I need. :)

**Comment by ukdtom** [comment] 2016-01-22 22:17
Thanks....If if I, or you get further ideas about what to try, then please return here...

I will for sure ;-)

**Comment by rimsky82** [comment] 2016-01-22 23:30
I copied the bundle folder from the program files tree to the appdata tree, and it worked.  Is that suppose to happen automatically at some point?

**Comment by SvenErik1968** [comment] 2016-01-23 09:55
@rimsky82 What is the folder structure under the appdata tree?
I have Plex installed on a separate drive, so my %LOCALAPPDATA%\Plex Media Server\ tree is empty.

**Comment by ukdtom** [comment] 2016-01-23 10:13
@rimsky82 3.Party bundles must ALWAYS be located in the AppData tree!

**Comment by SvenErik1968** [comment] 2016-01-23 10:35
@ukdtom What should be the folder structure there? Mine is empty.

**Comment by SvenErik1968** [comment] 2016-01-24 19:47
Finally managed to get it to work!
"The path where local application data is stored" was set to "D:\Plex\Plex Media Server\" so after some trial and error, found out that if it was placed in the "D:\Plex\Plex Media Server\Plex Media Server\Plug-ins" folder, it would run.

**Comment by ukdtom** [comment] 2016-01-24 20:23
Nice, and thanks for the feedback, so no error on our side then I guess....

And since chances of you guys been the only ones that would be faced with this, makes me considering writing an easy installer for WebTools for the Windows platform, like I did for the QNAP one.

Huge thanks for the feedback, and closing this one now

**Closed by ukdtom** 2016-01-24 20:23 UTC
Labels: Support
