### ISSUE TITLE
Restore the ability to delete subtitles downloaded by agents

### ISSUE THREAD

**Issue by OttoKerner** [dagalufh/WebTools.bundle#112] opened 2016-01-14 20:11 UTC
see title

reason:
the opensubtitles plugin caused at some point in the past duplicated subtitles. Practically at every library refresh the same subtitles were downloaded again and again.
I don't know whether it is still doing this now, but your tool was about the only way to remove the duplicates.
So please consider re-enabling this ability.

**Comment by ukdtom** [comment] 2016-01-14 20:21
Was intended as WAD, but logged as an enhancement for now...
But might have to wait, until UAS module has settled ;-)

**Comment by eduo** [comment] 2016-01-21 14:13
Is it possible to restore an older version that still supports it? By the time most people realize what the agent is doing it's already a mess of duplicates all over the place. My understanding is that just removing the subs from the agent's folder is not enough and the DB needs to also be changed but I could be wrong.

I'm being asked about how to cleanup the disaster made by the opensubtitles plugin (especially now that Sub-Zero seems to be doing this properly at last) and webtools was my "go-to" tool, but I now realize it no longer does this.

Also: When the functionality is put back in, could there be an option to search and delete all plug-in subtitles instead of per-file?

**Comment by ukdtom** [comment] 2016-01-21 23:26
You can find older versions here
https://github.com/dagalufh/WebTools.bundle/releases

But only one version can be installed at a time

And regarding delete all in one go is a good idea, but unsure about the impact here, so need to investigate that a bit more, before deciding

**Comment by ukdtom** [comment] 2016-02-28 10:49
Backend fixed with https://github.com/dagalufh/WebTools.bundle/commit/0122c6b9ec32d8e54fc3dd60870a23a4437f6ef1

Now miss the frontend

**Comment by ukdtom** [comment] 2016-03-03 20:39
Confirmed working

**Closed by ukdtom** 2016-03-03 20:39 UTC
Labels: enhancement
